### ISSUE TITLE
PageFault on init

### ISSUE THREAD

**Issue by KenDickey** [phoenix-rtos/phoenix-rtos-doc#152]
Greetings,
I am attempting to run the riscv64 test project on a RaspBerry Pi 4 under Raspian Linux.
Build seems to work fine, I get the same runtime error under both qemu and spike.
   sbaddaddr : 0 -> nil pointer??
I am pretty clueless here, but perhaps you can point me in the right direction.
Thanks much!
-KenD     [Ken dot Dickey at Whidbey dot COM]
---------------
bbl loader^M
^[[1mPhoenix-RTOS microkernel v. 2.97 rev: 2571d96
^[[0m^[[1m
Exception: 15 Store/AMO page fault
zero: 0000000000000000  ra : 000000000002604a   sp : 0000003fbffffee8   gp : 0000000000031fb8
 tp : 0000000000000000  t0 : 0000000000002118   t1 : 000000000001aca6   t2 : 000000000001aca4
 s0 : 0000000000000016  s1 : 000000000002ad60   a0 : 0000000000000000   a1 : 000000004004740f
 a2 : 0000003fbfffff54  a3 : 0000000000000038   a4 : 0000000000002158   a5 : 0000003fbfffff18
 a6 : 0000000000002160  a7 : 0000000000000059   s2 : 0000003fbfffffc8   s3 : ffffffffffffffff
 s4 : 0f0f0f0f0f0f0f0f  s5 : 0000003fbffffff0   s6 : 0000000000000001   s7 : 1212121212121212
 s8 : 1313131313131313  s9 : 1414141414141414  s10 : 1515151515151515  s11 : 1616161616161616
 t3 : 000000000001acc8  t4 : 000000000000000f   t5 : 0000000000000016   t6 : 0000000000000020
 ksp : 0000003fc0210ed8 sstatus : 00000000000c0000 sepc : 000000000002604a
 sbaddaddr : 0000000000000000 scause : 000000000000000f sscratch : 0000003fc0211000
^[[0m^[[1m
Exception: 15 Store/AMO page fault
zero: 0000000000000000  ra : 000000000002604a   sp : 0000003fbffffee8   gp : 0000000000031fb8
 tp : 0000000000000000  t0 : 0000000000002118   t1 : 000000000001aca6   t2 : 000000000001aca4
 s0 : 0000000000000016  s1 : 000000000002ad60   a0 : 0000000000000000   a1 : 000000004004740f
 a2 : 0000003fbfffff54  a3 : 0000000000000038   a4 : 0000000000002158   a5 : 0000003fbfffff18
 a6 : 0000000000002160  a7 : 0000000000000059   s2 : 0000003fbfffffc8   s3 : ffffffffffffffff
 s4 : 0f0f0f0f0f0f0f0f  s5 : 0000003fbffffff0   s6 : 0000000000000001   s7 : 1212121212121212
 s8 : 1313131313131313  s9 : 1414141414141414  s10 : 1515151515151515  s11 : 1616161616161616
 t3 : 000000000001acc8  t4 : 000000000000000f   t5 : 0000000000000016   t6 : 0000000000000020
 ksp : 0000003fc0210ed8 sstatus : 00000000000c0000 sepc : 000000000002604a
 sbaddaddr : 0000000000000000 scause : 000000000000000f sscratch : 0000003fc0211000
^[[0m^[[1m

**Comment by gerard5** [comment]
Hi,
thanks for catching that. You're right, there is a problem with `riscv64` in the master branch. I've identified the following changes that may cause the problem:

> * support for errno in thread local storage : https://github.com/phoenix-rtos/libphoenix/commit/079fa4447d26206aee88ea022753c6e28900a67c
> * scheduler invoked indirectly via interrupts_dispatch (using threads_timeintr) : https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/87aca363a3da0f7bd4ffd59723a5fbd375626318
> 

Included two quick patches below to make `phoenix-rtos` for `riscv64` work for both `spike` and `qemu-system-riscv64`. I appreciate your help. Tell us, if the fixes worked on your platform.

----
in `phoenix-rtos-kernel/proc/threads.c`revert changes to:
```diff
diff --git a/proc/threads.c b/proc/threads.c
index cc51d3b..3526500 100644
--- a/proc/threads.c
+++ b/proc/threads.c
@@ -44,6 +44,7 @@ struct {
 	rbtree_t id;
 
 	intr_handler_t timeintrHandler;
+	intr_handler_t scheduleHandler;
 
 #ifdef PENDSV_IRQ
 	intr_handler_t pendsvHandler;
@@ -1974,5 +1975,8 @@ int _threads_init(vm_map_t *kmap, vm_object_t *kernel)
 	hal_memset(&threads_common.timeintrHandler, NULL, sizeof(threads_common.timeintrHandler));
 	hal_timerRegister(threads_timeintr, NULL, &threads_common.timeintrHandler);
 
+	hal_memset(&threads_common.scheduleHandler, NULL, sizeof(threads_common.scheduleHandler));
+	hal_timerRegister(threads_schedule, NULL, &threads_common.scheduleHandler);
+
 	return EOK;
 }
```

and in `libphoenix/include/arch/riscv64/arch.h` temporarily disable line `__LIBPHOENIX_ARCH_TLS_SUPPORTED`, by commenting out.
```diff
diff --git a/include/arch/riscv64/arch.h b/include/arch/riscv64/arch.h
index 4ce4c9b..0f1b656 100644
--- a/include/arch/riscv64/arch.h
+++ b/include/arch/riscv64/arch.h
@@ -29,6 +29,6 @@
 #define _PAGE_SIZE 0x1000
 #define SIZE_PAGE _Pragma("GCC warning \"'SIZE_PAGE' is deprecated. Use _PAGE_SIZE from arch.h or PAGE_SIZE from limits.h (POSIX only)\"") _PAGE_SIZE
 
-#define __LIBPHOENIX_ARCH_TLS_SUPPORTED
+//#define __LIBPHOENIX_ARCH_TLS_SUPPORTED
 
 #endif
```

**Comment by KenDickey** [comment]
Closer.  Now gets OpenSBI before fault.
--------------------------
Raspian:RasPi4:~/Phoenix-RTOS >>> ./scripts/riscv64-generic-qemu.sh
WARNING: Image format was not specified for './scripts/../_boot/riscv64-generic-qemu/phoenix.disk' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.

OpenSBI v0.9
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name             : riscv-virtio,qemu
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 10000000Hz
Platform Console Device   : uart8250
Platform HSM Device       : ---
Platform SysReset Device  : sifive_test
Firmware Base             : 0x80000000
Firmware Size             : 244 KB
Runtime SBI Version       : 0.3

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x0000000002000000-0x000000000200ffff (I)
Domain0 Region01          : 0x0000000080000000-0x000000008003ffff ()
Domain0 Region02          : 0x0000000000000000-0xffffffffffffffff (R,W,X)
Domain0 Next Address      : 0x0000000080200000
Domain0 Next Arg1         : 0x0000000082200000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART ISA             : rv64imafdcsu
Boot HART Features        : scounteren,mcounteren,time
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 4
Boot HART PMP Address Bits: 54
Boot HART MHPM Count      : 0
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109
Phoenix-RTOS microkernel v. 2.97 rev: 2571d96

Exception: 15 Store/AMO page fault
zero: 0000000000000000  ra : 000000000002604a   sp : 0000003fbffffee8   gp : 0000000000031fb8
 tp : 0000000000000000  t0 : 0000000000002118   t1 : 000000000001aca6   t2 : 000000000001aca4
 s0 : 0000000000000016  s1 : 000000000002ad60   a0 : 0000000000000000   a1 : 000000004004740f
 a2 : 0000003fbfffff54  a3 : 0000000000000038   a4 : 0000000000002158   a5 : 0000003fbfffff18
 a6 : 0000000000002160  a7 : 0000000000000059   s2 : 0000003fbfffffc8   s3 : ffffffffffffffff
 s4 : 0f0f0f0f0f0f0f0f  s5 : 0000003fbffffff0   s6 : 0000000000000001   s7 : 1212121212121212
 s8 : 1313131313131313  s9 : 1414141414141414  s10 : 1515151515151515  s11 : 1616161616161616
 t3 : 000000000001acc8  t4 : 000000000000000f   t5 : 0000000000000016   t6 : 0000000000000020
 ksp : 0000003fc0210ed8 sstatus : 00000000000c0000 sepc : 000000000002604a
 sbaddaddr : 0000000000000000 scause : 000000000000000f sscratch : 0000003fc0211000

Exception: 15 Store/AMO page fault
zero: 0000000000000000  ra : 000000000002604a   sp : 0000003fbffffee8   gp : 0000000000031fb8
 tp : 0000000000000000  t0 : 0000000000002118   t1 : 000000000001aca6   t2 : 000000000001aca4
 s0 : 0000000000000016  s1 : 000000000002ad60   a0 : 0000000000000000   a1 : 000000004004740f
 a2 : 0000003fbfffff54  a3 : 0000000000000038   a4 : 0000000000002158   a5 : 0000003fbfffff18
 a6 : 0000000000002160  a7 : 0000000000000059   s2 : 0000003fbfffffc8   s3 : ffffffffffffffff
 s4 : 0f0f0f0f0f0f0f0f  s5 : 0000003fbffffff0   s6 : 0000000000000001   s7 : 1212121212121212
 s8 : 1313131313131313  s9 : 1414141414141414  s10 : 1515151515151515  s11 : 1616161616161616
 t3 : 000000000001acc8  t4 : 000000000000000f   t5 : 0000000000000016   t6 : 0000000000000020
 ksp : 0000003fc0210ed8 sstatus : 00000000000c0000 sepc : 000000000002604a
 sbaddaddr : 0000000000000000 scause : 000000000000000f sscratch : 0000003fc0211000

Exception: 15 Store/AMO page fault
zero: 0000000000000000  ra : 000000000001b934   sp : 0000003fbffff750   gp : 000000000001faf0
 tp : 0000000000000000  t0 : 0000003fbffff820   t1 : 0000000000000000   t2 : 0000000000012566
 s0 : 0000000000000002  s1 : 00000000000025c8   a0 : 0000000000000000   a1 : 0000003fbffff760
 a2 : 0000000000000000  a3 : 0000003fbffff820   a4 : 0000000000000028   a5 : 00000000000124e6
 a6 : 00000000000029e0  a7 : 0000000000000020   s2 : fffffffffffffffc   s3 : 00000000000003ff
 s4 : 0000003fbffff860  s5 : 0000000000000000   s6 : 000000000000002f   s7 : 0000000000000001
 s8 : 00000000000029c8  s9 : 0000000000000001  s10 : 00000000000021bc  s11 : 00000000000021b9
 t3 : 0000000000000000  t4 : 000000000001cb10   t5 : 0000000000000016   t6 : 00000000000025cd
 ksp : 0000003fc0209ed8 sstatus : 00000000000c0000 sepc : 000000000001b938
 sbaddaddr : 0000000000000000 scause : 000000000000000f sscratch : 0000003fc020a000
... ... ...

**Comment by KenDickey** [comment]
Now works as expected.  :)
